# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: '1.0'

stages:
- stage: Build App
  displayName: Build App
  jobs:
  - job: BubildApp
    displayName: Build App
    steps: 
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
        checkLatest: true
      displayName: 'Install Node.js'
    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'

- stage: Build and push docker image
  displayName: Build and push docker image
  jobs:  
  - job: BuildAndPush
    displayName: Build and push docker image
    steps:
    - task: Docker@2
      displayName: Build an image and push to Docker Hub
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'przemekulik/nodetours'
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/deploy/docker/Dockerfile'
        buildContext: .
        tags: |
          $(tag)

- stage: Pull, run and test nodetours container
  displayName: Pull, run and test nodetours container
  jobs:
  - job: PullRunAndTest
    displayName: Pull, run and test nodetours container
    steps: 
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # pull image
          docker pull przemekulik/nodetours:1.0
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # run container
          docker run -d --name nodetours -p 7777:7777 przemekulik/nodetours:1.0
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # call the API
          curl -I  http://localhost:7777
      